### ISSUE TITLE
Incompatibility with BetterEnd?

### ISSUE THREAD

**Issue by TheBlackEntity** [Suff99/TardisRefined#126]
### Issue description

Hey!

I'm currently playing a modpack with a friend.

After every restart, the server crashes due to something about BetterEnd and Tardis Refined.

This can be fixed by removing the mod, starting the server, stopping the server and re-adding the mod.

That's not really a fix though...

This is the error I get:
https://mclo.gs/u3BP4lg

This is the full log:
https://mclo.gs/zISC19R

Hope I'm not losing support just because I'm using Quilt...

### Steps to reproduce

1. Install BetterEnd and TardisRefined
2. Start the server
3. Stop the server
4. Start the server again

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Quilt Loader 0.18.10

### Tardis Refined version

Pre-release v0.1

**Comment by Suff99** [comment]
Are you able to replicate this in pure Fabric? We're not ignoring your report but none of us have interacted with Quilt yet and it would be good to know if this issue is to do with the mod or how another loader is handling our mod.

This does seem to be to do with how we store information and that might have already been addressed in a upcoming release but please validate Fabric for us

**Comment by TheBlackEntity** [comment]
Okay, seems like there's no issue with fabric instead of quilt.

I did not test anything besides the restarting though.

Hope you're still going to fix this. I love this mod!

(Some of my mods require me to use Quilt, so it's not possible to switch the entire modpack to fabric)

**Comment by 50ap5ud5** [comment]
We can look into Quilt compatibility in the future, but can't make any promises on that for the next release. It is already quite alot of work to maintain both Fabric and Forge versions, on top of updating to new Minecraft versions.

**Comment by MagmaBro123** [comment]
> We can look into Quilt compatibility in the future, but can't make any promises on that for the next release. It is already quite alot of work to maintain both Fabric and Forge versions, on top of updating to new Minecraft versions.

Architectury API exists.

**Comment by 50ap5ud5** [comment]
> > We can look into Quilt compatibility in the future, but can't make any promises on that for the next release. It is already quite alot of work to maintain both Fabric and Forge versions, on top of updating to new Minecraft versions.
> 
> Architectury API exists.

We are aware of Architectuary API, we currently have no need to use it. We are already using Architectuary's Loom version to develop for Fabric and Forge.

Developing for Quilt is certainly possible, however  we currently lack the time to look into it as the team has more important commitments to attend to such as full time work or studies. If you are capable and willing to offer assistance with Quilt support we would be open to discuss further. :)
