### ISSUE TITLE
Door textures

### ISSUE THREAD

**Issue by DaPuffer** [Suff99/TardisRefined#146]
### Issue description

If you somehow (probably with the /tardis_refined interior <interior_name_here. command) enter the TARDIS when the interior is changing,the door will have weird textures
![2023-05-09_20 52 12](https://github.com/CommandrMoose/TardisRefined/assets/132820752/a54157c3-3fd8-4338-862b-77e630a3a0e9)
![2023-05-09_20 54 56](https://github.com/CommandrMoose/TardisRefined/assets/132820752/ba79ea3c-b313-42f3-9cf4-131ce7dde303)
If you change the shell or the interior change timer ends,the door fixes itself

### Steps to reproduce

1. Get a Tardis
2. Initiate an interior change
3. Leave
4. Enter with the command or any other(yet undiscovered) method
5. The door is screwed up now.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.11

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
Yes. This is something I would like to address in time, currently the game does not sync fast enough when updating the door texture so if you're fast enough you can see the outdated texture on a new model. 

It doesn't impact gameplay, so it's low priority to fix but it definetly needs addressed

**Comment by Jeryn99** [comment]
Fixed in 1.20.2
