### ISSUE TITLE
Crash after taking off

### ISSUE THREAD

**Issue by AnonymouseCow** [Suff99/TardisRefined#154]
### Issue description

I took off with the TARDIS, then flipped all of the necessary switches. Later, I logged off and the server stopped, then I logged back in later with the console beeping and smoking, the screen was also shaking, I was able to open the door but couldn't leave (No portal appeared). Whenever I tried to flip a switch, it burned me. The game had highlighted a switch like it does normally during flight but right clicking it didn't work, I had then left clicked it and it made the success sound it usually makes at the end of flights and it landed however I could not leave still so I took off and then the server crashed.

I expected to still be in flight and to not crash.

### Steps to reproduce

1. Take off
2. Flip the switches
3. Log off
4. Stop server
5. Rejoin and mess with the controls

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.14.21

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/EcMCvxyL

**Comment by AnonymouseCow** [comment]
When I started the server after the initial crash, I was able to land and the Tardis was deposited at 0, 43, 0.

**Comment by thejudge156** [comment]
Are you sure you clicked all the switches?

**Comment by AnonymouseCow** [comment]
Yes, I am sure, it played the neat little XP level up sound! Either way I still believe the server should not have crashed.

**Comment by AnonymouseCow** [comment]
I figured out that the error occurs no matter what after a server restart and then taking off, I believe that the TARDIS forgets where it is and then proceeds to error out and crash.

**Comment by Suff99** [comment]
Fixed
