### ISSUE TITLE
The TARDIS love to land underground 

### ISSUE THREAD

**Issue by Craftman780** [Suff99/TardisRefined#164]
### Issue description

When I set the increment switch to 1000, and randomize it a few times, she sets the y value to 150 herself, surely so she can land aboveground, but nope, she lands in the negatives most of the times. 

### Steps to reproduce

1. Set the increment switch to x1000

2. Randomize the coordinates

3. See in the message above the hotbar, as well as in the computer bank the y value is set to y=150

4. Takeoff

5. Step outside, or check the computer bank upon landing to see she landed in the negative y values.

6. Be thoroughly confused 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.2.21

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
Fixed
