### ISSUE TITLE
[Fabric] [Bug?] Strange "Alternate" Dimensions

### ISSUE THREAD

**Issue by CodedKyoko** [Suff99/TardisRefined#165]
### Issue description

I was messing around with the fabric version of Tardis Refined when I went to the Dim panel to go to the nether, I noticed there was 5 other dimensions, "Alternate 1, 2,3,4 and 5" going to them they all appear to be different variations of the over world, with different terrain generation, This did not occur while I was playing via forge, Pictured below is Alternate1
![image](https://github.com/Suff99/TardisRefined/assets/129420497/bc695e11-3d8a-41ea-9983-b70ef8267595)  
![image](https://github.com/Suff99/TardisRefined/assets/129420497/093c2dc3-2b17-4f2b-a767-4058c0bad14f)

### Steps to reproduce

1.Load fabric Tardis Refined
2.Scroll through the dim panel,
3.Select Alternate[1-5]
4. demat remat etc
5. look around

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.14.12

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://mclo.gs/u1xanpD

**Comment by Suff99** [comment]
@50ap5ud5 Looks like Immersive Portals dimensions have different IDs on Fabric?

**Comment by Suff99** [comment]
Fixed
