### ISSUE TITLE
[FABRIC] Airlock Door's Bugged?

### ISSUE THREAD

**Issue by TLGKK23** [Suff99/TardisRefined#167]
### Issue description

So Lately on my Mc server we added Tardis Refined and are loving it but we are having a issue with the rooms past the airlock. The area back there wont allow any Blocks to be placed and the other door's wont open and you cant break into them so any advice how to fix it would be great.

### Steps to reproduce

1: Load the Mod on fabric.
2: Grow the tardis and go inside
3: Enter the backrooms ans try to break any Blocks beside the growth stone.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 1.19.2  0.14.21

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
This was intended for the version you're playing, it will be allowed in coming versions

**Comment by TLGKK23** [comment]
Alright No Problem
