### ISSUE TITLE
TARDIS Entities Datpack Bug

### ISSUE THREAD

**Issue by Musa5150** [Suff99/TardisRefined#170]
### Issue description

When I type false to ignore entities in the datapack creation command it doesnt say my entities and if i try to put true that doesnt work either.

### Steps to reproduce

1. Create a datapack using the /data command
2. Type false in the ignore entities part
3. Doesn't save the entities

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.2.0 1.19.2

### Tardis Refined version

v1.0

### Other relevant versions

All the updated versions of Suff's Doctor Who mods, human companions, War Of The Worlds, Immersive Portals, optifine, ad astra, essentials, K9

**Comment by Suff99** [comment]
Can you make a video of the issue? Having some issues understanding

**Comment by Musa5150** [comment]
When you try create a datapack using the /tardis-refined data command, it doesn't allow you to save entities like armour stands etc.
