### ISSUE TITLE
Dynamic Trees Leaves Hydration crash

### ISSUE THREAD

**Issue by B4SlC** [Suff99/TardisRefined#171]
### Issue description

When Landing a tardis on "Dynamic Leaves" from the dynamic trees mod, after a few seconds the server crashes and the chunk is inaccesible. 
the crash report talks about trhe leaves asking for a hydration level

tested it 5 times, it only ever happens when the tardis is touching any leaves.

### Steps to reproduce

1.get Dynamic Trees
2. Land the tardis on a tree
3. watch it crash

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Curse Forge Loader 0.237.1

### Tardis Refined version

v1.0

### Other relevant versions

DynamicTreesBOP-1.19.2-3.1.1.jar
DynamicTrees-1.19.2-1.1.0-BETA10.jar
DynamicTreesVampirism-1.19.2-1.3.0.jar
DynamicTreesPlus-1.19.2-1.1.3.jar

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/B4SlC/58dfbdc21699ca943d8fb55fb94c7214

**Comment by AlienXtream** [comment]
can you recreate the crash with JUST TR and dynamic trees?

**Comment by Suff99** [comment]
Seems to be a common issue with them:

https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/82

https://github.com/DynamicTreesTeam/DynamicTrees/issues/675
