### ISSUE TITLE
cloned tardis model during teleportation

### ISSUE THREAD

**Issue by CakeNapoleon** [Suff99/TardisRefined#172]
### Issue description

Иногда после перемещения ТАРДИС, если вы перезапустите игру и вернетесь к последней точке без использования ТАРДИС, вы обнаружите нефункциональную копию оболочки ТАРДИС, которую невозможно сломать без использования команд. Я думаю это связано с тем, что при телепортации чанк в мире не загружается, а ждет процесса удаления оболочки ТАРДИС, а при перезапуске игры процесс пропадает и не выполняется. Думаю, если постоянно загружать чанк, в котором находится ТАРДИС, проблема уйдет, но немного ухудшит производительность.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 1.19.2 43.3.2

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
Duplicate of https://github.com/Suff99/TardisRefined/issues/152
