### ISSUE TITLE
No option to reduce Root Plant generation?

### ISSUE THREAD

**Issue by JackSpidy** [Suff99/TardisRefined#185]
### Issue description

Just wondering if there is any way to reduce the generation of Root Plants, they seem fairly abundant and I'd like to reduce their spawn rate.

### Steps to reproduce

N/A

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.24

### Tardis Refined version

v1.0.1

**Comment by Jeryn99** [comment]
Hello! You can! You will need to create a datapack that targets this file 
https://github.com/Suff99/TardisRefined/blob/new_assets/forge/src/generated/resources/data/tardis_refined/worldgen/placed_feature/tardis_root_cluster.json

:)
