### ISSUE TITLE
CRASH - server wont start again when a TARDIS exist

### ISSUE THREAD

**Issue by Giro100** [Suff99/TardisRefined#95]
### Issue description

a local server crashes when i try to start it after i created a tardis

### Steps to reproduce

1. create a server, i created a local one.
2. grow/spawn a tardis shell.
3. enter it thus creating its dim.
4. close the server and try to restart it.
5. server crash.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric loader 0.14.12

### Tardis Refined version

Pre-release v0.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)
[crash-2023-02-23_15.24.38-server.txt](https://github.com/CommandrMoose/TardisRefined/files/10830990/crash-2023-02-23_15.24.38-server.txt)

_No response_

**Comment by CommandrMoose** [comment]
We cannot help without a crash report.

**Comment by Giro100** [comment]
forgot to upload it

**Comment by Suff99** [comment]
Create a new crash report, this one is just a thread dump

**Comment by Giro100** [comment]
[crash-2023-02-25_15.41.45-server.txt](https://github.com/CommandrMoose/TardisRefined/files/10831283/crash-2023-02-25_15.41.45-server.txt)

**Comment by Suff99** [comment]
Are you able to re-create this with V1?

**Comment by Suff99** [comment]
Fixed
